Tickets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('', include("ticketing.urls", namespace="tickets")),
    path('', include("main.urls", namespace="main")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views as app

app_name = "main"
urlpatterns = [
    path('', app.home, name="home"),
    path('signup/', app.signup, name="signup"),
]

ticketing/urls.py
from django.urls import path
from ticketing import views as app

app_name = "tickets"
urlpatterns = [
    path('', app.home, name="home"),
    path('create/', app.create, name="create"),
    path('edit/<int:id>', app.edit, name="edit"),
    path('delete/<int:id>', app.delete, name="delete"),
    path('view/<int:id>', app.view, name="view"),
    path('view/<int:id>/comment', app.view, name="view_comment"),
    path('adjuntos/<str:uid>', app.adjuntos, name="adjunto"),
]

ticketing/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    NIVELES = {
        1: "NIVEL 1",
        2: "NIVEL 2",
        3: "NIVEL 3",
        4: "NIVEL 4"
    }
    nombre = models.CharField(max_length=100)
    nivel = models.SmallIntegerField(choices=NIVELES)

    def __str__(self):
        return self.nombre

class Ticket(models.Model):
    ESTADOS = {
        "O": "ABIERTO",
        "P": "PENDIENTE",
        "C": "COMPLETADO"
    }
    asunto = models.CharField(max_length=300)
    mensaje = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    estado = models.CharField(max_length=1, choices=ESTADOS, default="O")
    prioridad = models.PositiveSmallIntegerField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    creacion = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.asunto

def adjunto_upload_to(instance, filename):
    return "comentarios/{}/{}_{}".format(instance.ticket.id, instance.autor.username, filename)

class Comentario(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    publicacion = models.DateTimeField(auto_now=False, auto_now_add=True)
    mensaje = models.TextField()
    adjunto = models.FileField(upload_to=adjunto_upload_to, blank=True)

    def __str__(self):
        return self.mensaje[0:10]

ticketing/forms.py
from django import forms
from ticketing.models import Ticket, Comentario

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ["asunto", "mensaje", "categoria", "prioridad"]
        widgets = {
            "asunto": forms.TextInput(attrs={"class": "form-control"}),
            "mensaje": forms.Textarea(attrs={"class": "form-control"}),
            "categoria": forms.Select(attrs={"class": "form-select"}),
            "prioridad": forms.NumberInput(attrs={"class": "form-control", "min": "1", "max": "5"}),
        }

class TicketEditForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ["asunto", "mensaje"]
        widgets = {
            "asunto": forms.TextInput(attrs={"class": "form-control"}),
            "mensaje": forms.Textarea(attrs={"class": "form-control"}),
        }
class TicketStaffEditForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ["estado", "categoria", "prioridad"]
        widgets = {
            "estado": forms.Select(attrs={"class": "form-control"}),
            "categoria": forms.Select(attrs={"class": "form-select"}),
            "prioridad": forms.NumberInput(attrs={"class": "form-control", "min": "1", "max": "5"}),
        }
class ComentarioForm(forms.Form):
    mensaje = forms.CharField(required=True)
    adjunto = forms.FileField(required=False)

    mensaje.widget = forms.Textarea(attrs={"class": "form-control", "rows":"3", "placeholder": ""})
    adjunto.widget = forms.FileInput(attrs={"class": "form-control", "placeholder": "Opcional", 'accept': 'application/pdf,application/msword,image/gif,image/jpeg,image/png,image/webp,text/csv'})

ticketing/views.py
from django.http import FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from .forms import TicketForm, ComentarioForm, TicketEditForm, TicketStaffEditForm
from .models import Ticket, Comentario
from django.contrib import messages
import os.path

# Create your views here.
@login_required
def home(respuesta):
    tickets = Ticket.objects.all()
    return render(respuesta, "ticketing/home.html", {"tickets":tickets})

@login_required
def create(respuesta):
    form = TicketForm()
    if respuesta.method == "POST":
        form = TicketForm(respuesta.POST, instance=Ticket(autor=respuesta.user))
        if form.is_valid():
            form.save()
            messages.success(respuesta, '¡Ticket creado correctamente!')
            return redirect("tickets:home")
        else:
            messages.error(respuesta, form.errors)
    return render(respuesta, "ticketing/create.html", {"form":form})

@login_required
def edit(respuesta, id):
    ticket = get_object_or_404(Ticket, id=id) # pk=id o id=id funcionan | si no existe la ID, 404
    form = TicketForm(respuesta.POST or None, instance=ticket)
    if respuesta.user == ticket.autor:
        form = TicketEditForm(respuesta.POST or None, instance=ticket)
    if respuesta.user.is_staff and respuesta.user != ticket.autor:
        form = TicketStaffEditForm(respuesta.POST or None, instance=ticket)
    if ticket.estado == "C" and not respuesta.user.is_staff:
        messages.error(respuesta, '¡El ticket está cerrado!')
        return redirect("tickets:home")
    if respuesta.method == "POST" and form.is_valid():
        form.save()
        messages.success(respuesta, '¡Ticket editado correctamente!')
        return redirect("tickets:home")
    else:
        messages.error(respuesta, form.errors)
    if ticket.autor != respuesta.user and not respuesta.user.is_staff:
        return redirect("tickets:home")
    return render(respuesta, "ticketing/edit.html", {"ticket":ticket ,"form": form})

@login_required
def delete(respuesta, id):
    # messages.error(respuesta, "Esta funcion no se encuentra habilitada.")
    # return redirect("tickets:home")
    if respuesta.user.is_staff:
        ticket = get_object_or_404(Ticket, id=id)
        ticket.delete()
        messages.success(respuesta, '¡Ticket eliminado correctamente!')
    else:
        messages.error(respuesta, '¡No tienes permisos!')
    return redirect("tickets:home")

@login_required
def view(respuesta, id):
    ticket = get_object_or_404(Ticket, id=id)
    comentarios = Comentario.objects.filter(ticket_id=id).order_by('-publicacion')
    form = ComentarioForm(respuesta.POST or None, respuesta.FILES or None)
    if respuesta.method == "POST" and form.is_valid():
        archivo = respuesta.FILES.get('adjunto', None)
        nuevo = Comentario(ticket=ticket, autor=respuesta.user, mensaje=form.cleaned_data['mensaje'], adjunto=archivo)
        nuevo.save()
        messages.success(respuesta, '¡Comentario enviado!')
        return redirect("tickets:view", id=id)
    else:
        messages.error(respuesta, form.errors)
    return render(respuesta, "ticketing/view.html", {"ticket":ticket, "form":form, "comentarios":comentarios})

def adjuntos(respuesta, uid):
    archivo = str("adjuntos/{}".format(uid))
    # verificar si el archivo existe
    if os.path.isfile(archivo):
        return FileResponse(
                open(archivo, "rb"),
                as_attachment=False,
                filename=uid # o obtener el nombre y formato del archivo
        )
    messages.error(respuesta, "Adjunto no encontrado.")
    return redirect("tickets:home")

templates/ticketing/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="content-box">
        <h1>Bienvenido a Tickets!</h1>
        <h3>Vamos a generar un ticket</h3>
        <div style="padding: 20px;">
            <form action="{% url 'tickets:create' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button style="width: 100%;" class="btn btn-success" type="submit">Crear</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/ticketing/delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Bienvenido a Tickets!</h1>
    <h3>Eliminando ticket {{ id }}</h3>
</div>
{% endblock %}

templates/ticketing/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="content-box">
        <h1>Editar un ticket</h1>
        <h3>Modificando ticket: [{{ ticket.id }}] {{ ticket.asunto }}</h3>
        {% include "mensajes.html" %}
        <div style="padding: 20px;">
            <form action="#" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button style="width: 100%;" class="btn btn-warning" type="submit">Editar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/ticketing/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="content-box">
        <h1>Bienvenido a Tickets!</h1>
        <h3>Clic en el botón para generar un nuevo ticket.</h3>
        <a class="btn btn-success" href="{% url 'tickets:create' %}">Crear</a>
        <hr>
        {% include "mensajes.html" %}
        {% if tickets %}
            <div class="row">
                {% for ticket in tickets %}
                    <div class="col-auto" style="{% if ticket.estado == "O" %}{% elif ticket.estado == "P" %}opacity:0.7;{% elif ticket.estado == "C" %}opacity:0.2;{% endif %}">
                        <div class="card animate__animated animate__fadeInLeft" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {% if ticket.estado == "O" %}
                                        <span class="ticket-status" style="--c1: #3ffbbb; --c2: #28cc95;"></span>
                                    {% elif ticket.estado == "P" %}
                                        <span class="ticket-status" style="--c1: #ffbb33; --c2: #cc9528;"></span>
                                    {% elif ticket.estado == "C" %}
                                        <span class="ticket-status" style="--c1: #ff002f; --c2: #cc2828;"></span>
                                    {% endif %}
                                    {{ ticket.asunto }}
                                </h5>
                                <p class="card-text">{{ ticket.mensaje }}</p>
                                <div class="progress" role="progressbar" aria-label="Danger striped example" aria-valuenow="{{ ticket.prioridad }}" aria-valuemin="0" aria-valuemax="100">
                                    <div class="progress-bar progress-bar-striped bg-danger overflow-visible" style="width: calc(calc({{ ticket.prioridad }} * 100%) / 5)">Prioridad {{ ticket.prioridad }}🔥</div>
                                </div>
                            </div>
                            <div class="card-body">
                                <a href="{% url 'tickets:view' ticket.id %}" class="card-link">Ver</a>
                                {% if ticket.autor == request.user or request.user.is_staff %}
                                {% include 'components/editar.html' %}
                                {% endif %}
                                {% if request.user.is_staff %}
                                {% include 'components/eliminar.html' %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/ticketing/view.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    {% if ticket %}
    <div class="content-box">
        <div class="row">
            <div class="col d-flex align-items-center">
                {% if ticket.estado == "O" %}
                    <span class="ticket-status" style="--c1: #3ffbbb; --c2: #28cc95;"></span>
                {% elif ticket.estado == "P" %}
                    <span class="ticket-status" style="--c1: #ffbb33; --c2: #cc9528;"></span>
                {% elif ticket.estado == "C" %}
                    <span class="ticket-status" style="--c1: #ff002f; --c2: #cc2828;"></span>
                {% endif %}
                <div class="ms-3">
                    <h1>{{ ticket.asunto }}</h1>
                    <p style="font-size: 15px;">
                        Publicado por {{ ticket.autor.username }}, {{ ticket.creacion }}
                    </p>
                </div>
            </div>
            <div class="col-auto">
                <div class="d-flex gap-2 mb-3">
                    {% if ticket.autor == request.user or request.user.is_staff %}
                    {% include 'components/editar.html' %}
                    {% endif %}
                    {% if request.user.is_staff %}
                    {% include 'components/eliminar.html' %}
                    {% endif %}
                </div>
            </div>
        </div>
        <zero-md>
            <template>
                <style>
                    p {
                        color: white;
                        font-size: 25px;
                    }
                </style>
            </template>
            <script type="text/markdown">{{ ticket.mensaje }}</script>
        </zero-md>
        <hr>
        {% include "mensajes.html" %}
        {% if ticket.estado != "C" %}
            {% if ticket.autor == user or user.is_staff %}
                <form style="padding: 20px;" enctype="multipart/form-data" action="{% url 'tickets:view_comment' ticket.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <div class="input-group">
                                <label class="input-group-text" for="id_mensaje">Mensaje</label>
                                {{ form.mensaje }}
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="input-group mb-3">
                                <label class="input-group-text" for="id_adjunto">Adjunto</label>
                                {{ form.adjunto }}
                            </div>
                            <button style="width: 100%;" class="btn btn-success" type="submit">Enviar</button>
                        </div>
                    </div>
                </form>
            {% endif %}
        {% else %}
            <div class="alert alert-danger" role="alert">
                Ticket cerrado. Ya no se aceptan comentarios al thread.
            </div>
        {% endif %}
        {% if comentarios %}
            {% for comentario in comentarios %}
                <div style="padding: 10px;">
                    <div class="card mb-3 bg-transparent border-2 text-white">
                        <div class="card-body">
                          <h5 class="card-title mb-1">
                            {% if comentario.autor.is_staff %}<span class="fst-italic text-warning">Soporte</span> {% endif %}{{ comentario.autor.username }}
                        </h5>
                          <p class="card-text text-reset small mb-2">
                            {{ comentario.publicacion }}
                        </p>
                          <div class="card-text">
                            <zero-md>
                                <template>
                                    <style>
                                        p {
                                            color: white;
                                            font-size: 20px;
                                        }
                                        a {
                                            color: cyan;
                                        }
                                    </style>
                                </template>
                                <script type="text/markdown">{{ comentario.mensaje }}</script>
                            </zero-md>
                          </div>
                        {% if comentario.adjunto %}
                           Archivo adjunto <a href="{{ comentario.adjunto.url }}">[{{ comentario.adjunto.name }}]</a>
                        {% endif %}
                        </div>
                      </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% endif %}
</div>
{% endblock %}