Tickets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('', include("ticketing.urls", namespace="tickets")),
    path('', include("main.urls", namespace="main")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views as app

app_name = "main"
urlpatterns = [
    path('', app.home, name="home"),
    path('signup/', app.signup, name="signup"),
]

ticketing/urls.py
from django.urls import path
from ticketing import views as app

app_name = "tickets"
urlpatterns = [
    path('', app.home, name="home"),
    path('create/', app.create, name="create"),
    path('edit/<int:id>', app.edit, name="edit"),
    path('delete/<int:id>', app.delete, name="delete"),
    path('view/<int:id>', app.view, name="view"),
    path('view/<int:id>/comment', app.view, name="view_comment"),
    path('adjuntos/<str:uid>', app.adjuntos, name="adjunto"),
]

templates/components/editar.html
<button onclick="location.href='{% url 'tickets:edit' ticket.id %}';" type="button" class="btn btn-success">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"></path>
    </svg>
    Editar
</button>

templates/components/eliminar.html
<button onclick="eliminar()" type="button" class="btn btn-danger">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
    </svg>
    Eliminar
</button>
<script>
    function eliminar() {
        Swal.fire({
            title: "¿Eliminar el Ticket?",
            text: "Esta acción no se puede deshacer.",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#FF0000",
            cancelButtonColor: "#808080",
            confirmButtonText: "Si, eliminalo",
            cancelButtonText: "Cancelar"
        }).then((result) => {
            if (result.isConfirmed) {
                fetch("{% url 'tickets:delete' ticket.id %}").then(() => {
                    window.location.replace("{% url 'tickets:home' %}");
                });
            }
        });
    }
</script>